version: '3.8'

services:
  claude-todoist-api:
    build: .
    container_name: claude-todoist-api-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - RATE_LIMIT_WINDOW=15
      - RATE_LIMIT_MAX=100
      - CORS_ORIGIN=*
      - LOG_LEVEL=debug
      - DEFAULT_PROJECT_NAME=Inbox
      - DEFAULT_PRIORITY=2
    volumes:
      - ./logs:/app/logs:rw
      - ./src:/app/src:ro  # For development hot reload
    networks:
      - claude-todoist-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  claude-todoist-network:
    driver: bridge

volumes:
  logs:
    driver: local